### ISSUE TITLE
When do you plan to release v5?

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#105]
Hi @bpuig!

When do you plan to release v5? Now to use the library in the v5 version, one needs to use 
`composer require bpuig/laravel-subby:dev-main` which is not a perfect solution. 

I'd rather already switched to using
`composer require bpuig/laravel-subby:^5`

**Comment by bpuig** [comment]
Hello! You can see here in [project](https://github.com/bpuig/laravel-subby/projects/1) the issues that have to be solved before release. Once I've got them I can release v5. Right now there are only 3 left. One of them I'm working on it, and the others should not take long.
Date? I don't know, but I hope soon

**Comment by boryn** [comment]
IMHO https://github.com/bpuig/laravel-subby/issues/82 is not that necessary for v5. But if you think it won't take long, of course it would be a nice to have.

**Comment by bpuig** [comment]
I've got to think #82 a little bit more. I think v5 is ready.
