### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by muarachmann** [bpuig/laravel-subby#121]
Hi there.

+1 for this package however was wondering if there is some form of documentation or any ETA?

**Comment by bpuig** [comment]
Hello, maybe I'm too used to it that it seems hard to find for others: https://bpuig.github.io/laravel-subby/v6.x/

I'll try to make the readme more specific 😓

**Comment by muarachmann** [comment]
> Hello, maybe I'm too used to it that it seems hard to find for others: https://bpuig.github.io/laravel-subby/v6.x/
> 
> I'll try to make the readme more specific 😓

Thanks that works
