### ISSUE TITLE
Bpuig \ Subby \ Exceptions\ DuplicateException

### ISSUE THREAD

**Issue by sajjad-talebi** [bpuig/laravel-subby#145]
Hi,
After the end of the subscription, when the user wants to renew the plan subscription, he encounters this error.
Full error report link:
[link](https://flareapp.io/share/A7EjQQB5#F58)

**Comment by bpuig** [comment]
You have a `renew` function, why are you storing the same subscription again?

**Comment by sajjad-talebi** [comment]
Thanks, this has been fixed.
