### ISSUE TITLE
Subscription feature price

### ISSUE THREAD

**Issue by aeq-dev** [bpuig/laravel-subby#150]
Hello, Thanks for this great package.
Let's say I have a plan A with three features F1,F2 and F3
Each feature has its own price,
The bill amount is calculated based on usage of each feature
Example : 
F1 => price $1.6  usage : 30
F2 => price $0.9 usage 15
F3 => price $1.2 usage 12
Client invoice amount = (1.6 x 30) + (0.9 x 15) + (1.2 x 12) = $75.9

How can I achieve this ? thanks

**Comment by aeq-dev** [comment]
May be we can add price field to both plan_features and plan_subscription_features tables

**Comment by bpuig** [comment]
Hello, at the moment there is no support for metered subscriptions or priced features. Sorry

**Comment by aeq-dev** [comment]
Thanks @bpuig , in fact I've just added price filed to plan features table and all is fine :)
