### ISSUE TITLE
Changelog link

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#24]
I'm so happy I have found your fork :)

I just wanted to let know that the link to changelog is wrong in the README.md (should have the extension .html instead of .md)

(And actually that document is missing some information available at https://github.com/bpuig/laravel-subby/releases)

**Comment by bpuig** [comment]
Hello!! It's nice to see someone here, I thought I was alone :smiley: 

Solved everything in #26 and released [v3.0.2](https://github.com/bpuig/laravel-subby/releases/tag/3.0.2), also updated docs.

Thanks!
