### ISSUE TITLE
Graceful handling of double features create

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#30]
When I run the below code twice (or just try to create the feature with an existing tag)

```php
$user->subscription('primary')->features()->create(
            [
                'tag'                 => 'pictures_per_social_profile',
                'name'                => 'Pictures per social profile',
                'value'               => 30,
                'sort_order'          => 10,
                'resettable_period'   => 1,
                'resettable_interval' => 'month'
            ]
        );
```

I get:
_SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-pictures_per_social_profile' for key 'plan_subscription_features.plan_subscription_features_subscription_id_tag_unique' (SQL: insert into `plan_subscription_features` (`tag`, `name`, `value`, `sort_order`, `resettable_period`, `resettable_interval`, `subscription_id`, `updated_at`, `created_at`) values (pictures_per_social_profile, Pictures per social profile, 30, 10, 1, month, 1, 2021-05-13 06:46:21, 2021-05-13 06:46:21))_

Maybe better would be to return false as a not successful query?

The same goes for creating plan with the same tag (`$plan = Plan::create()`)

**Comment by boryn** [comment]
And the same for double assigning the `$user->newSubscription` with the same tag

**Comment by bpuig** [comment]
> And the same for double assigning the `$user->newSubscription` with the same tag

This is fixed e3d2f336b1c2ffa1331e2a9c195f5ca5b3970e64 here because is a custom method. But in the first example, `create` is a native laravel function, so better validate before input. Rules are in model.

**Comment by bpuig** [comment]
Something like this? 1d915d606934712899e606433a61154beecceb34 It'll be a bit intensive since there are many insert methods. Any suggestion?

**Comment by boryn** [comment]
Let me fetch it and I'll have a bit later

**Comment by boryn** [comment]
I suggested this solution: https://github.com/bpuig/laravel-subby/pull/48
