### ISSUE TITLE
Default name of subscription

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#32]
As majority of implementations would use just one subscription, maybe the name 'main' could be a default one and used 'in the background'?

I mean possibility of using `$user->subscription->` instead of every time attaching 'main' `$user->subscription('main')->`
and during creation maybe using `$user->newMainSubscription()` ?

**Comment by bpuig** [comment]
Done in 50f93a6 with a new variable in config.

From new docs...

## Subscriber's main subscription

Since usually projects work with only one subscription or one primary, you have to set the tag for it in the
config `main_subscription_tag`.

By default is `main`.

```php
// config/subby.php
return [
    'main_subscription_tag' => 'main',
    ...
];
````

Then:

```php
// This:
$user->mainSubscription();

// Equals
$user->subscription('main');
```
