### ISSUE TITLE
getFeatureByTag() in Subscription

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#33]
To get to the subscription feature (for example to update it) we need to use `$user->subscription('main')->features()->where('tag', 'social_profiles')`. It would be great to use a simpler form like `$user->subscription('main')->getFeatureByTag('social_profiles')`

**Comment by bpuig** [comment]
Done in one of the latest commits in [add_subscription_features](https://github.com/bpuig/laravel-subby/tree/add_subscription_features) branch, I lost track because I refactored A LOT. I'm going to push an alpha now.
