### ISSUE TITLE
Behaviour of modified plan features

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#35]
As far as I understand, when the plan features change, users stay with the "old" features rules? One needs to use `$user->subscription('main')->syncPlanFeatures();` to reflect changes in the user's configuration? 

This part of `syncPlanFeatures()` is only mentioned in `plan-subscription-model.md` - I think it's worth mentioning as well in the `plan-subscription-feature-model.md` because it's not that obvious.

What if we would need to update feature set for all the users? Will `syncPlanFeatures()` work on the Collection of subscribers?

**Comment by bpuig** [comment]
Ok, I'll try to improve docs.

> What if we would need to update feature set for all the users? Will `syncPlanFeatures()` work on the Collection of subscribers?

Yes, you'd have to loop every user. I think it's a bit difficult to mass update, since there are some comparisons there. I'm no expert, but if you come with a method to mass update I'd be glad to implement it.

**Comment by bpuig** [comment]
Added d0bcefd0da8ecf86db69a585b173e0b74a4c0b74

If you think it's enough, you may close this issue.
