### ISSUE TITLE
syncWithPlan / syncPlan mixup

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#36]
There is a naming mixup

![image](https://user-images.githubusercontent.com/807297/118096302-76f16380-b3d1-11eb-9b3e-dd468f442484.png)

**Comment by boryn** [comment]
PS. Is `syncPlan(null, null, true)` the same as `syncPlanFeatures()` ?

**Comment by boryn** [comment]
PS2. syncPlan() could work on a Collection of subscribers as well

**Comment by bpuig** [comment]
> There is a naming mixup

Yep, changed name and forgot to update docs.

**Comment by bpuig** [comment]
> PS. Is `syncPlan(null, null, true)` the same as `syncPlanFeatures()` ?

`syncPlan(null, false, true)` is. Second param is `bool`.

**Comment by bpuig** [comment]
Fixed in 1177fef
