### ISSUE TITLE
Some broken links in the docs

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#37]
For example at https://github.com/bpuig/laravel-subby/tree/4.0.0-alpha.3/docs the link "plan" goes to https://github.com/bpuig/laravel-subby/blob/4.0.0-alpha.3/models/plan-model.md

![image](https://user-images.githubusercontent.com/807297/118097528-1a8f4380-b3d3-11eb-85bc-dec621db96a2.png)

**Comment by bpuig** [comment]
Its because they are ment to be built with (Vuepress)[https://vuepress.vuejs.org/]. Install it, navigate to dir and launch `vuepress dev`. I don't know how to make them compatible to be read here and also in vuepress. I'll take a look to see if there is possible and if not maybe I'll add a note.

**Comment by bpuig** [comment]
It's not compatible :cry: , install [vuepress](https://vuepress.vuejs.org/) navigate to docs directory and use `vuepress dev` to build docs.
