### ISSUE TITLE
More details about plan_subscription_features in the Create a Subscription doc

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#38]
Maybe it's worth mentioning in `plan-subscription-model.md` in the 'Create a Subscription' section that now the features got copied to `plan_subscription_features`? I mean an explanation that a subscriber does not use feature set directly from `plan_features`, that `plan_features` is only a template. Someone may think you create a plan, you attach it to subscription and use definitions from `plan_features`.

**Comment by bpuig** [comment]
Explained in d0bcefd0da8ecf86db69a585b173e0b74a4c0b74
