### ISSUE TITLE
Laravel version 6.x

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#45]
As far as I understand, job batching is now used at https://github.com/bpuig/laravel-subby-schedule and only there, the Laravel 8 is required.

Could you allow for Laravel 6 as well here? I think it should work. I will give it a try as I have one project with v6.

**Comment by bpuig** [comment]
I can't see anything in this list that is on the project https://laravel.com/docs/7.x/upgrade#upgrade-7.0
So I'll do it

**Comment by bpuig** [comment]
Done in 3714f34
