### ISSUE TITLE
Default of resettable_interval

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#46]
Defing this feature

```php
new PlanFeature(
     [
         'tag'        => 'api',
         'name'       => 'API Module',
         'value'      => false,
         'sort_order' => 70,
     ]
 ),
```

and later seeing 'month' in the `resettable_interval` is a little bit misleading. Wouldn't it better to have `resettable_interval` nullable with default 'null'?

**Comment by bpuig** [comment]
It does not accept null, always need an hour, day or month. It's used to calculate Period.
See validation:
`'resettable_interval' => 'sometimes|in:hour,day,week,month',`

By default it is not resettable, because is reset 0 month.

**Comment by boryn** [comment]
Yes, the `resettable_period` is 0, so it is not resettable, and that's why seeing 'month' at `resettable_interval` is very confusing.

**Comment by boryn** [comment]
So do you decide to leave it this way? I still suggest that if `resettable_period` is 0, `resettable_interval` should be `null`

**Comment by bpuig** [comment]
Yes, it's not critical and changing means I'd have to refactor things that are already working.
