### ISSUE TITLE
Update of invoice fields upon changePlan($plan)

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#51]
I have a $plan with `invoice_interval` of a value 'year'. I do:

```php
$plan::find(2); // the one with `invoice_interval` set to 'year'
$subscription = $user->subscription();
$subscription->changePlan($plan);
```

After checking the db, I have indeed changed `plan_id`, `price` and `currency` but not `invoice_period` and `invoice_interval` fields.  As `$syncInvoicing` is by default `true` in `changePlan()` I would expect that `invoice_period` and `invoice_interval` got updated as well in the `plan_subscriptions` table?

The `ends_at` was properly extended by a year from now.

**Comment by bpuig** [comment]
You are right.
Fixed in 714ba02a71569fb87a8e035f65620b89c55aca7e
