### ISSUE TITLE
Handling of renewals of trials

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#57]
I still wonder how to properly handle renewals of the trial subscriptions.

Scenario:

- user registers at the website
- at the moment of registration gets a subscription with a trial (Basic / Pro - does not matter, but with trial days)
- consumes X times the features (which are registered with `recordFeatureUsage()`)
- at the end of the trial decides to pay 
- payment is successful and now, upon issuing `->renew()` all usages consumed during trial **are reset** as in the `renew()` method there is `$subscription->usage()->delete();`

Am I missing something? I'd rather kept the usages consumed during trial.

**Comment by bpuig** [comment]
Someone asked about how does it work https://github.com/rinvex/laravel-subscriptions/issues/67 in the original package, never got response. I guess we'll have to figure out and decide what's best.

In my opinion, we should be able to include the trial on the period or exclude it (pre-period). 

About renewal, I guess trial ending should not renew. Package users should code a cron job that checks for ended trials and charge them. Most would be solved by having the ability of chosing wether to place the trial before the subscription period or inside the subscription period so you end up with charging the period or charging the period and giving trial as a gift.

**Comment by boryn** [comment]
(I think we can continue the discussion at https://github.com/bpuig/laravel-subby/issues/58)
