### ISSUE TITLE
Email notifications about expiring subscriptions

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#73]
Hi! I was wondering about a scheduler for email notifications about expiring subscriptions. Thereotically the mechanim should not be that complicated.

I would see a config with time before end divided per subscription tag:
`['main']['sub'] => [7, 3, 1] //days before subscription ends`

or even expressed in hours so that we can send an email 4 or 1 hour before the end.
`['primary']['trial'] => [72, 24, 4, 1]`

Scheduler would pick up subscribers (in the loop according to the config) and send a notification with 'mail' channel given as an example. If someone would like to use some other like sms / web push, they'd need to override the base notification method:

```php
Notification::send(
    $subscribers,
    new ExpiringSubscriptionNotification(
	//
    )
);
```

**Comment by bpuig** [comment]
It's a good idea. But notifications are not as simple as they seem, they can be more complex, like using services (like email relays), channels, etc. keeping track of who has been notified, etc
It has to be deeply thought
