### ISSUE TITLE
Scope for getting subscriptions with ending period should not return trial subs

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#74]
Scope `$subscriptions = PlanSubscription::findEndingPeriod(3)->get();` will unnecessary return trial subscriptions which were not prolonged (activated). 

While using a trial plans either `ends_at` should be set to the same value as `trial_ends_at` or the above mentions scope should return only active subscriptions.

**Comment by bpuig** [comment]
Take a look at this [branch](https://github.com/bpuig/laravel-subby/tree/subscription_trial_improvement). Careful, because it will be v5 and has migrations. Docs have been updated for Plans.
