### ISSUE TITLE
Grace period

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#79]
(I'll share some more thoughts regarding the upcoming new v5 version)

I saw you decided to remove the grace period fields because as I understood they had no coverage in the code?

But IMHO it would be good to implement the functionality of the grace period. There are situations where people want to continue with our app, but there were some issues with their card (expired, stolen, used daily limit, etc.) they could be even unaware of. Until we try to charge the money, neither we or the user know about the problem. 

And when this situation arises, we should give them some `grace_period` (always expressed in days?) to solve the issue with the card and not abruptly stop access to the app/features.

I think using of grace period should only modify the behaviour of `isActive()` and not `hasEnded()`. Maybe an extra method like `isInGracePeriod()` could be useful as well.

**Comment by boryn** [comment]
I think it would be great to have the grace period in the upcoming v5. What are your thoughts @bpuig?

**Comment by bpuig** [comment]
Are you thinking per plan or global config?

**Comment by boryn** [comment]
Global config could be useful, but probably would not be enough. I see its behaviour similar to features, so that grace period is defined in the plan and copied to `plan_subscriptions`. I mean that the majority of customers can have for example, the default 3 days of grace period, but some can have exceptions of 5 or 10 days.

**Comment by bpuig** [comment]
Done!
