### ISSUE TITLE
Fallback plan

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#81]
Let's imagine a user has a "Pro" subscription. They decide to cancel or just not to renew. Actually then we cut them off of all the features, even the ones available in the "Free" plan. 

Maybe it would be good to implement an optional fallback/default plan? If they intentionally cancel, we can `changePlan()` for them, but if the subscription just expires, the user is left with all features blocked because `canUseFeature()` will just return `false` :).

**Comment by bpuig** [comment]
Good idea, should be easy to do with just a config.
