### ISSUE TITLE
Keeping track of subscription changes

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#82]
The `plan_subscriptions` table shows the current state of the users' subscriptions, but we have no idea of their history. And this information is often very valuable. 

Of course, someone would (at least should) keep track of the payments, but it does not give the full image of subscription changes.

I'd see this functionality inside the library itself, with a simple table `plan_subscription_log` with fields:

- id
- tag
- subscriber_type
- subscriber_id
- plan_id
- name
- price
- currency
- action
- timestamp

where `action` could be one of: 'trial_started' / 'renewed' (treated as well as started) / 'canceled'.

This way we could know what user did with their subscription, when they decided to upgrade/downgrade/renew/cancel, how long they were with us, did they have any gaps in the subscription, etc. It's often very valuable information for the support team.

**Comment by bpuig** [comment]
I increased the stale period, because it was short, let's keep this going on.

**Comment by aeq-dev** [comment]
+1 Nice feature, any updates on this ? Thanks

**Comment by Montreys** [comment]
any updates on this?

**Comment by bpuig** [comment]
This is a one-man project, made personally, there is no company behind or economic interest, so thing will be done when they are done and if they are done. Hope you understand if a feature takes long or it is not made at all. Thanks
