### ISSUE TITLE
Scheduler back to the main library?

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#83]
With all these things that pop up over and over again like:

- (double) renew
- renew subscription upon the trial finishes
- change plan (downgrade / upgrade) upon next renewal

I thought maybe it would be a good idea to make again a scheduler an integral part of this package?

But for wider compatibility I would resign from job batches. Actually, I would even resign from jobs altogether. Why not just make the implementation in the command (`$schedule->command(...)->everyMinute()->runInBackground();`)? Commands already run in background and using jobs seems to me superfluous.  This would also demand less requirements - just running the scheduler and no need to configure queue drivers or worker.

For example, upon issuing a renewal, the task could be saved into `plan_subscription_schedules` to be run upon `ends_at` (or `trial_ends_at`) and scheduler will pick it up upon right moment and make appropriate changes.

**Comment by bpuig** [comment]
Just the other day I was thinking this, that I should revisit the schedule package and see if I can drop the job batch and bring it back here again here, since it's very useful.

**Comment by bpuig** [comment]
Shut up, stale bot! :stuck_out_tongue:
