### ISSUE TITLE
Features are not returned according to the `sort_order`

### ISSUE THREAD

**Issue by boryn** [bpuig/laravel-subby#91]
Actually, I have just discovered that features and features in relationships are not returned in the order set by the `sort_order` column.

**Comment by bpuig** [comment]
Yes, it's your duty to order them on your query. If package orders them it may interfere with user's custom selects and orders.

**Comment by boryn** [comment]
I think, maybe it would be worthy to insert a sentence about it in the docs? Seeing the `sort_order` column I mistakenly assumed the sorting is handled by the library.

**Comment by bpuig** [comment]
Fixed 2624be2a21875c275afa16e2865a98b84f87db5e
